seeds: [42, 137]
datasets:
  - exchange_rate
  - electricity
  - solar
  - wiki
  - taxi
  - m3_monthly
  - m3_quarterly
  - m3_yearly
  - m3_other
  - m4_hourly
  - m4_daily
  - m4_weekly
  - m4_monthly
  - m4_quarterly
  - m4_yearly
  - m5
  - tourism_monthly
  - tourism_quarterly
  - tourism_yearly
  - nn5
  - car_parts
  - dominick
  - fred_md
  - san_francisco_traffic
  - pedestrian_count
  - hospital
  - covid_deaths
  - kdd_2018
  - cif_2016
  - australian_electricity_demand
  - bitcoin
  - rideshare
  - vehicle_trips
  - temperature_rain
  - m1_yearly
  - m1_quarterly
  - m1_monthly
  - rossmann
  - walmart
  - restaurant
models:
  nbeats:
    - key: context_length_multiple
      values: [1, 2, 4, 8]
    - key: [num_stacks, num_blocks]
      values: [[4, 5], [30, 1], [30, 2]]
