experiment: bee
model: REDSDS
dataset: bee
seg_labels: true
only_segmentation: True
d_min: 20
d_max: 50
batch_size: 32
context_length: 120
prediction_length: 0
freq: H
x_dim: 8
obs_dim: 4
log_dir: ./results/exps1-d/bee/{timestamp}/logs/
log_steps: 500
model_dir: ./results/exps1-d/bee/{timestamp}/models/
save_steps: 500
num_categories: 3
num_steps: 20000
num_samples: 1
objective: elbov2
flat_learning_rate: false
warmup_start_lr: 5.e-5
learning_rate: 0.0002
grad_clip_norm: 10.
weight_decay: 1.e-5
warmup_steps_lr: 2000
initial_switch:
  mlp_hiddendim: 8
discrete_transition:
  takes_x: true
  takes_y: true
continuous_transition:
  model_type: linear
  tied_cov: false
  trainable_cov: true
  fixed_sigma: 0.02
  max_scale: 2
  mlp_hiddendim: 8
emission:
  model_type: linear
  tied_cov: true
  trainable_cov: true
  fixed_sigma: 0.02
  max_scale: 2
inference: 
  tied_cov: false
  trainable_cov: true
  fixed_sigma: 0.02
  max_scale: 2
  embedder: brnn  # transformer or brnn
# BRNN params
  embedding_rnndim: 16
  embedding_rnnlayers: 1
# Transformer params
  embedding_trans_usepe: true
  embedding_trans_nhead: 1
  embedding_trans_embdim: 4
  embedding_trans_mlpdim: 16
  embedding_trans_nlayers: 1
# Causal RNN
  use_causal_rnn: true
  causal_rnndim: 16
# MLP
  mlp_hiddendim: 32
initial_state:
  tied_cov: true
  trainable_cov: true
  fixed_sigma: 0.02
  max_scale: 2
  mlp_hiddendim: 8
control:
  mlp_hiddendim: 64
  has_ctrl: false
  z: false
  x: false
  inference: false
  emb_dim: 0
  feat_dim: 0
  n_staticfeat: 0
  n_timefeat: 0
transform_target: false
transform_only_scale: false
use_jacobian: false
forecast:
  num_samples: 100
  deterministic_z: true
  deterministic_x: false
  deterministic_y: true
switch_t_annealing: true
switch_t_init: 100.
switch_t_min: 10.
switch_t_annealing_rate: 0.95
switch_t_annealing_steps: 100
switch_t_annealing_kickin_steps: 5000
dur_t_annealing: true
dur_t_init: 10.
dur_t_min: 1.
dur_t_annealing_rate: 0.95
dur_t_annealing_steps: 100
dur_t_annealing_kickin_steps: 5000
cont_ent_anneal: 1.0
# Unused or inconsequential
xent_annealing: false
xent_init: 100.
xent_rate: 0.95
xent_steps: 50
xent_kickin_steps: 2000