# The Docker image to run your workspace in. Defaults to gitpod/workspace-full
image: gitpod/workspace-full
# Command to start on workspace startup (optional)
tasks:
  - command: python -m pip install --upgrade pip
  - command: pip install -r requirements/requirements-mxnet.txt

# Ports to expose on workspace startup (optional)
ports:
  - port: 8000
    onOpen: open-preview

vscode:
    extensions:
        - littlefoxteam.vscode-python-test-adapter@0.3.16:tZ/6xOSSdKUaq6JCUVkD+A==