[tool.black]
line-length = 100


[tool.pytest.ini_options]
testpaths = "test"
addopts = "-v --doctest-modules --color=yes --cov=src/ncad --cov-report term-missing"
filterwarnings = [
    "ignore::DeprecationWarning:tensorboard.*:",
    "ignore::DeprecationWarning:tables.*:",
    "ignore::UserWarning",
]
