name: Build nightly Windows

on:
  push
  #schedule:
    # * is a special character in YAML so you have to quote this string
    # nightly:
    #- cron:  '0 0 * * *'

jobs:
  build:

    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7]
        platform: [windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Extract release version tag
      run: |
        $tmp=(Invoke-WebRequest -Uri https://api.github.com/repos/awslabs/gluon-ts/releases/latest).Content | 
        ConvertFrom-Json |
        Select-Object tag_name
      shell: powershell
    - name: Cleanup version tag for use with Git
      run: |
        $tmp=$tmp.psobject.properties.value.trim() 
      shell: powershell
    - name: Install dependencies
      run: |
        git clone https://github.com/awslabs/gluon-ts --branch $tmp
        cd gluon-ts
        python -m pip install --upgrade pip
        pip install -r requirements/requirements-mxnet.txt
        pip install -e ".[shell]"
        pip install -r requirements/requirements-test.txt
    - name: Test with pytest
      run: |
        cd gluon-ts
        pytest -m 'not (gpu or serial)' --cov src/gluonts --cov-report=term --cov-report xml test
