name: Doctests

on: [push, pull_request]

jobs:
  test:
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        python-version: ['3.11']
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        uv sync --python ${{ matrix.python-version }} --extra arrow --extra test

    - name: Test with pytest
      run: |
        uv run pytest -n2 --doctest-modules \
          src/gluonts/core \
          src/gluonts/dataset \
          src/gluonts/model \
          src/gluonts/time_feature \
          src/gluonts/zebras \
          src/gluonts/maybe.py \
          src/gluonts/itertools.py