name: Doctests

on: [push, pull_request]

jobs:
  test:
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        python-version: ['3.9']
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install other dependencies
      run: |
        python -m pip install -U pip
        pip install -r requirements/requirements-test.txt
    - name: Test with pytest
      run: |
        pytest -n2 --doctest-modules \
          src/gluonts/core \
          src/gluonts/itertools.py
