name: Ruff & Docformat

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        check: ["ruff", "docformatter"]

    steps:
    - uses: actions/checkout@v7

    - name: Install uv
      uses: astral-sh/setup-uv@v8
      with:
        version: "latest"

    - name: Set up Python
      run: uv python install 3.12

    - name: Install dependencies
      run: uv sync --python 3.12

    - name: Ruff (Flake8)
      if: matrix.check == 'ruff'
      working-directory: src/
      run: uv run ruff check .

    - name: Docformatter
      if: matrix.check == 'docformatter'
      run: uv run docformatter --check -r src/