name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  publish-to-pypi:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Get tags
      run: git fetch --tags origin
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install -U pip
        python -m pip install setuptools wheel
    - name: Create `dist` folder
      run: |
        python setup.py sdist bdist_wheel
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        skip_existing: true
