name: Python package

on: [push, pull_request]

jobs:
  build:

    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7]
        # todo: add windows-latest
        platform: [ubuntu-latest]
    
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/requirements-mxnet.txt
        pip install -e ".[shell]"
        pip install -r requirements/requirements-test.txt
    - name: Test with pytest
      run: |
        pytest -m 'not (gpu or serial)' --cov src/gluonts --cov-report=term --cov-report xml test
