name: Style checks

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Style check with Black
      run: |
        pip install black -c requirements/requirements-setup.txt
        black --check src test examples
    - name: Check license headers
      run: python .devtools/license check src test
