name: R Tests

on: [push, pull_request]

jobs:
  test:
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        python-version: ['3.9']
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '3.5.3'
    - name: Install Python dependencies
      run: |
        python -m pip install -U pip
        pip install .
        pip install -r requirements/requirements-test.txt
        pip install -r requirements/requirements-extras-r.txt
    - name: Install R dependencies
      run: |
        sudo apt-get install libcurl4-openssl-dev
        Rscript -e 'install.packages(c("forecast", "nnfor"), repos="https://cloud.r-project.org")'
    - name: Test with pytest
      run: |
        pytest --ignore test/ext/r_forecast/test_r_hierarchical_predictor.py test/ext/r_forecast
