name: XGBoost Tests

on: [push, pull_request]

jobs:
  test:
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        python-version: ['3.12']
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v7

    - name: Install uv
      uses: astral-sh/setup-uv@v8.2.0
      with:
        version: "latest"

    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        uv sync --python ${{ matrix.python-version }} --extra test --extra rotbaum --extra rotbaum-extra

    - name: Test with pytest
      run: |
        uv run pytest -n2 --timeout 120 --doctest-modules test/ext/rotbaum